language: minimal

services:
  - docker

before_install:
  - echo "Start building and pushing Docker images"

script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag udagram-frontend phamnguyen18/udagram-frontend:local
  - docker tag udagram-api-feed phamnguyen18/udagram-api-feed:v1a
  - docker tag udagram-api-user phamnguyen18/udagram-api-user:v1a
  - docker tag udagram-reverseproxy phamnguyen18/udagram-reverseproxy:v1a
  - docker push phamnguyen18/udagram-frontend:local
  - docker push phamnguyen18/udagram-api-feed:v1a
  - docker push phamnguyen18/udagram-api-user:v1a
  - docker push phamnguyen18/udagram-reverseproxy:v1a
